# 1. When squirrels get together for a party, they like to have cigars. A squirrel party is successful when the number of cigars is between 40 and 60, inclusive. Unless it is the weekend, in which case there is no upper bound on the number of cigars. Return True if the party with the given values is successful, or False otherwise. Hints: Use simple boolean expressions to solve.

In [ ]:
def cigar_party(cigars, is_weekend):
    # Put your code here!

    
# Leave this stuff alone! It will test your code.    
print "It's the weekend!"
for i in xrange(30,80,10):
    print i,cigar_party(i,True)
    
print "\nAnother weekday..."
for i in xrange(30,80,10):
    print i,cigar_party(i,False)
    

# 2. Given a string name, e.g. "Bob", return a greeting of the form "Hello Bob!". hello_name('Bob') → 'Hello Bob!'


In [ ]:
def hello_name(name):
    #Put your code in here!




# Leave this stuff alone! It will test your code.
names = ['Bob','Susan','Carolyn','Zathura']

for name in names:
    print hello_name(name)

# 3. Given a list of ints, return True if the list is length 1 or more, and the first element and the last element are equal. 

In [ ]:
# A list takes the form a = [b,c,d].
# 

def same_first_last(nums):
    # Put your code here!
    
    
    
#Test it yourself! Remember to test edge cases!

# 4. Given a number, return true if it is even and false if it is odd.

In [ ]:
def even_odd(num):
    # Put your code here!
    
    
#Test it yourself! Remember to test edge cases!

# 5. Use string.replace() to replace "matlab" with "python".

In [ ]:
my_string = "I code in matlab!"

# Set values for a and b to replace "matlab" with "python".
a = 
b = 
new_string = my_string.replace(a,b)


# See the change!
print my_string
print new_string


# 6. Given 2 strings, a and b, return the number of the positions where they contain the same length 2 substring. So "xxcaazz" and "xxbaaz" yields 3, since the "xx", "aa", and "az" substrings appear in the same place in both strings. 


In [ ]:
def string_match(a,b):
    # Put your code here!
    
    
#Test it yourself! Remember to test edge cases!

# Examples of NumPy

In [14]:
from numpy import *

a = array([ [ 0, 1, 2, 3, 4],
     [10,11,12,13,14],
     [20,21,22,23,24],
     [30,31,32,33,34] ])

print a[0,0] # indices start by zero

0


In [15]:
print a[-1] # last row

[30 31 32 33 34]


In [16]:
print a[1:3,1:4] # subarray

[[11 12 13]
 [21 22 23]]


In [17]:
i = array([0,1,2,1]) # array of indices for the first axis
j = array([1,2,3,4]) # array of indices for the second axis
print a[i,j]

[ 1 12 23 14]


In [18]:
print a[a<13] # boolean indexing

[ 0  1  2  3  4 10 11 12]


In [20]:
b1 = array( [True,False,True,False] ) # boolean row selector
print a[b1,:]

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [19]:
b2 = array( [False,True,True,False,True] ) # boolean column selector
print a[:,b2]

[[ 1  2  4]
 [11 12 14]
 [21 22 24]
 [31 32 34]]


# Example of matplotlib

In [1]:
"""
Demo of scatter plot on a polar axis.

Size increases radially in this example and color increases with angle (just to
verify the symbols are being scattered correctly).
"""

import numpy as np
import matplotlib.pyplot as plt


N = 150
r = 2 * np.random.rand(N)
theta = 2 * np.pi * np.random.rand(N)
area = 200 * r**2 * np.random.rand(N)
colors = theta

ax = plt.subplot(111, projection='polar')
c = plt.scatter(theta, r, c=colors, s=area, cmap=plt.cm.hsv)
c.set_alpha(0.75)

plt.show()

# Example of Simple Python Class

In [29]:
class Employee:

    empCount = 0
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
        Employee.empCount += 1
   
    def displayCount(self):
        print "Total Employee %d" % Employee.empCount
        
    def displayEmployee(self):
        print "Name : ", self.name,  ", Salary: ", self.salary
        
jim = Employee('jim',50)
jim.displayCount()
jim.displayEmployee()

dwight = Employee('dwight',60)
dwight.displayCount()



Total Employee 1
Name :  jim , Salary:  50
Total Employee 2
